name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
api-version: '1.18'
main: com.gmail.willramanand.RamMMO.RamMMO
depend: [RamSkills]
softdepend: [Vault]
commands:
  mmo:
    description: Base command for RamMMO.
permissions:
  rammmo.boss:
    default: op
  rammmo.item:
    default: op
