name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
api-version: '1.18'
main: com.gmail.willramanand.RamMMO.RamMMO
depend: [AureliumSkills]
softdepend: [Essentials]
commands:
  mmo:
    description: Base command for RamMMO.
    permission: rammmo.mmo
permissions:
  rammmo.mmo:
    default: true
  rammmo.mmo.boss:
    default: op
