name: RamMMO
version: 1.4.0-SNAPSHOT
description: This plugin adds MMO elements to your Spigot server.
author: ${project.author}
api-version: '1.18'
main: com.gmail.willramanand.RamMMO.RamMMO
depend: [RamSkills]
softdepend: [Vault]
commands:
  mmo:
    description: Base command for RamMMO.
permissions:
  rammmo.mmo:
    default: true
  rammmo.boss:
    default: op
  rammmo.item:
    default: op
